
export const Images = {
  google_plus: require("@assets/images/google_plus.png"),
  splash: require("@assets/images/splash.png"),
  logo: require("@assets/images/logo.png"),
  ic_home: require("@assets/images/ic_home.png"),
  ic_home_fill: require("@assets/images/ic_home_fill.png"),
  ic_chat: require("@assets/images/ic_chat.png"),
  ic_chat_fill: require("@assets/images/ic_chat_fill.png"),
  ic_sell: require("@assets/images/ic_sell.png"),
  ic_myads: require("@assets/images/ic_myads.png"),
  ic_myads_fill: require("@assets/images/ic_myads_fill.png"),
  ic_profile: require("@assets/images/ic_profile.png"),
  ic_profile_fill: require("@assets/images/ic_profile_fill.png"),
  ic_location: require("@assets/images/ic_location.png"),
  ic_attach: require("@assets/images/ic_attach.png"),
  ic_reaction: require("@assets/images/ic_reaction.png"),
  ic_send: require("@assets/images/ic_send.png"),
  ic_category_all: require("@assets/images/ic_category_all.png"),
  ic_dashboard_fill: require("@assets/images/ic_dashboard_fill.png"),
  ic_dashboard: require("@assets/images/ic_dashboard.png"),
  ic_favourite_fill: require("@assets/images/ic_favourite_fill.png"),
  ic_favourite: require("@assets/images/ic_favourite.png"),
  ic_bell: require("@assets/images/ic_bell.png"),
  ic_boost: require("@assets/images/ic_boost.png"),
};